##
# This file contains a complete list of available application configuration
# keys. Copy it to development.yml and test.yml, fill those in, and DO NOT
# commit them to version control.
#

# Database host.
db_host: postgres
# Database port.
db_port: 5432
# Database name.
db_database: quince
# Database username.
db_username: postgres
# Database password.
db_password: postgres
secret_key_base: whateverdoesntmatter