##
# This file contains a complete list of available application configuration
# keys. Copy it to development.yml and test.yml, fill those in, and DO NOT
# commit them to version control.
#

# Database host.
db_host: localhost
# Database port.
db_port: 5432
# Database name.
db_database: database_name
# Database username.
db_username: username
# Database password.
db_password: password
# Required by Rails. Generate using `rails secret`.
secret_key_base: