name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test in Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run the tests
        run: |
          docker-compose up --build --exit-code-from quince